services:
  db:
    container_name: db
    image: bitnami/postgresql:latest
    environment:
      - POSTGRESQL_USERNAME=botato
      - POSTGRESQL_PASSWORD=botato
      - POSTGRESQL_DATABASE=botato
    ports:
      - 5432:5432
  lavalink:
    container_name: lavalink
    image: fredboat/lavalink:master
    ports:
      - 2333:2333
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml